asensioInit=function(){
  chi_1=0.5
  chi_cp=chi_1
  chi_2=1000
  g=200
  tau=0.25
  gamma1=1.45
  gamma2=2.5
  r_h=0.005
  epsilon2=0.005
  theta=0.5
  w=1
  alpha=1
  UC=w/alpha
  psi=0.5
  a1=0.875
  a2=0.05
  lambda13=1.25
  lambda11=2.5
  lambda12=1.25
  lambda14=0.2
  lambda20=0.45
  lambda21=1.25
  lambda23=1.25
  lambda22=2.5
  lambda24=0.2
  gbY=1.1
  p=(1+theta)*w
  gby=gbY*p
  PCB=0
  r_gb=r_h
  Y=(g*p-PCB)/((tau/(1+tau))-r_gb*gbY)
  T=tau/(1+tau)*Y
  G=g*p
  y=Y/p
  N_d=y/alpha
  WB=w*N_d
  s=y
  c=s-g
  C=c*p
  gb=gbY*Y
  r_m=r_h+epsilon2
  r_l=r_m+2*epsilon2
  r_cp=r_l
  s_e=s
  inv_t=s_e*(gamma1-gamma2*r_l)
  inv=inv_t
  INV_t=inv*UC
  INV=inv*UC
  cp=chi_1*INV_t
  l=(1-chi_1)*INV_t
  F_f=C+G-T-WB-r_l*l-r_cp*cp
  YD=C
  V_h=(c-a1*YD/p)/a2*p
  YD_e=YD
  V_he=V_h
  gb_h=(lambda20-lambda21*r_cp+lambda22*(r_gb)-lambda23*r_m)*V_he-lambda24*YD_e
  lambda10=(cp+lambda13*r_m*V_h-lambda11*(r_cp)*V_h+lambda12*r_gb*V_h+lambda14*YD)/V_h
  epsilon1=r_cp-r_h
  M=V_h-gb_h-cp
  F_b=-(WB+F_f+r_m*M+r_cp*cp-C)
  gb_cb=gb-gb_h
  H=gb_cb
  sink("asensioInit.csv")
  cat(paste("chi_1,",chi_1,"\n"))
  cat(paste("chi_2,",chi_2,"\n"))
  cat(paste("chi_cp,",chi_cp,"\n"))
  cat(paste("g,",g,"\n"))
  cat(paste("tau,",tau,"\n"))
  cat(paste("gamma1,",gamma1,"\n"))
  cat(paste("gamma2,",gamma2,"\n"))
  cat(paste("r_h,",r_h,"\n"))
  cat(paste("epsilon2,",epsilon2,"\n"))
  cat(paste("theta,",theta,"\n"))
  cat(paste("w,",w,"\n"))
  cat(paste("alpha,",alpha,"\n"))
  cat(paste("psi,",psi,"\n"))
  cat(paste("a1,",a1,"\n"))
  cat(paste("a2,",a2,"\n"))
  cat(paste("lambda10,",lambda10,"\n"))
  cat(paste("lambda11,",lambda11,"\n"))
  cat(paste("lambda12,",lambda12,"\n"))
  cat(paste("lambda13,",lambda13,"\n"))
  cat(paste("lambda14,",lambda14,"\n"))
  cat(paste("lambda20,",lambda20,"\n"))
  cat(paste("lambda21,",lambda21,"\n"))
  cat(paste("lambda22,",lambda22,"\n"))
  cat(paste("lambda23,",lambda23,"\n"))
  cat(paste("lambda24,",lambda24,"\n"))
  cat(paste("s,",s,"\n"))
  cat(paste("s_e,",s_e,"\n"))
  cat(paste("inv,",inv,"\n"))
  cat(paste("INV,",INV,"\n"))
  cat(paste("YD,",YD,"\n"))
  cat(paste("YD_e,",YD_e,"\n"))
  cat(paste("V_h,",V_h,"\n"))
  cat(paste("V_he,",V_he,"\n"))
  cat(paste("r_gb,",r_gb,"\n"))
  cat(paste("r_m,",r_m,"\n"))
  cat(paste("r_l,",r_l,"\n"))
  cat(paste("r_cp,",r_cp,"\n"))
  cat(paste("M,",M,"\n"))
  cat(paste("cp,",cp,"\n"))
  cat(paste("gb,",gb,"\n"))
  cat(paste("gb_cb,",gb_cb,"\n"))
  cat(paste("gb_h,",gb_h,"\n"))
  cat(paste("H,",H,"\n"))
  cat(paste("l,",l,"\n"))
  cat(paste("epsilon1,",epsilon1,"\n"))
  sink()
}